version: 2
jobs:
  build:
    docker:
      - image: dtcristo/gke-builder:latest

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce

      - run:
          name: Build image
          command: |
            docker build \
              -t dtcristo/gke-builder:${CIRCLE_BUILD_NUM} \
              -t dtcristo/gke-builder:latest \
              .

      - run:
          name: Push image
          command: |
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
            docker push dtcristo/gke-builder
