version: 2
jobs:
  build:
    docker:
      - image: docker:stable

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build image
          command: |
            TAG=$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
            IMAGE=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
            docker build \
              -f Dockerfile \
              -t $IMAGE:$TAG \
              -t $IMAGE:latest \
              .

      - run:
          name: Push image
          command: |
            TAG=$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
            IMAGE=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push $IMAGE:$TAG
