version: 2
jobs:
  build:
    docker:
      - image: dtcristo/gke-builder:latest

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build image
          command: |
            gcloud docker -- build \
              -t dtcristo/gke-builder:${CIRCLE_BUILD_NUM} \
              -t dtcristo/gke-builder:latest \
              .

      - run:
          name: Push image
          command: |
            gcloud docker -- login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
            gcloud docker -- push dtcristo/gke-builder
