version: 2
jobs:
  build:
    docker:
      - image: dtcristo/gke-builder:latest

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build image
          command: |
            IMAGE=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
            TAG=$CIRCLE_BUILD_NUM
            docker build \
              -f Dockerfile \
              -t ${IMAGE}:${TAG} \
              -t ${IMAGE}:latest \
              .

      - run:
          name: Push image
          command: |
            IMAGE=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
            TAG=$CIRCLE_BUILD_NUM
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
            docker push ${IMAGE}
